### ISSUE TITLE
Another project for reference

### ISSUE THREAD

**Issue by danemacmillan** [farnots/iCloudDownloader#2]
I just stumbled upon your CLI tool, and in your README there are some future improvements listed. I've been using https://github.com/Obbut/iCloud-Control for several months, so I wanted to point it out to you, given the similarity in goals, and also to serve as a reference should you be curious what others are doing in Swift in relation to iCloud.

**Comment by farnots** [comment]
Yeah thanks for the link, I use [iCloud-Control](https://github.com/Obbut/iCloud-Control) to help me build the first version of the CLI tool. I'll definitly try to take some time to improve it
